### PR TITLE
Troubleshoot build-test

### PR DESCRIPTION
**Pull request by iocanel**

### CODE REVIEW

**Comment by cmoulliard** [comment]
Still same error => https://github.com/quarkiverse/quarkus-argocd/actions/runs/11036981349/job/30656746764?pr=41

**Comment by cmoulliard** [comment]
Here is the hack to add the extension and to avoid the error till we found the root cause
```
awk '
/<dependencyManagement>/ { in_dep_management = 1 }
/<\/dependencyManagement>/ { in_dep_management = 0 }
/<\/dependencies>/ && !in_dep_management {
    print "    <dependency>\n        <groupId>io.quarkiverse.argocd</groupId>\n        <artifactId>quarkus-argocd</artifactId>\n        <version>999-SNAPSHOT</version>\n    </dependency>"
}
{ print }
' pom.xml > tmp.xml && mv tmp.xml pom.xml
```
@iocanel

**Comment by cmoulliard** [comment]
Great news as `build-and-test` job succeeded and ArgoCD file has been well generated and is not empty
```
ArgoCD Applications generated:
code-with-quarkus-deploy
## Check if the file has been generated ...
Argo CD file has been generated
repoURL field exists within the generated Argo CD generated file !
```

**Review by cmoulliard — APPROVED** [review]
Should we create an issue to keep track about the fact that you forced the QuarkusBootStrap builder of quarkus to also load the Argo CD jar ?

@iocanel

**Comment by iocanel** [comment]
> Should we create an issue to keep track about the fact that you forced the QuarkusBootStrap builder of quarkus to also load the Argo CD jar ?
> 
> @iocanel

I will create some related issues.

**Pull request merged**
