### PR TITLE
Introduce AppProject support

### PR DESCRIPTION
**Pull request by iocanel**
Resolves: #49

### CODE REVIEW

**Comment by cmoulliard** [comment]
I did a test using the following parameters 
```
./mvnw clean package -DskipTests -Dquarkus.argocd.namespace=aaa -Dquarkus.argocd.applicationNamespace=bbb
```
but we got a very toooo long ArgoCD Yaml generated and containing items duplicated

```
---
resourceList:
  applicationList:
    items:
    - apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: code-with-quarkus-deploy
        namespace: aaa
      spec:
        destination:
          namespace: aaa
          server: https://kubernetes.default.svc
        project: code-with-quarkus
        source:
          helm:
            valueFiles:
            - values.yaml
          path: .helm/kubernetes/code-with-quarkus
          repoURL: https://github.com/quarkiverse/code-with-quarkus.git
          targetRevision: HEAD
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          retry:
            backoff:
              duration: 5s
              factor: 2
              maxDuration: 10m
          syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - ApplyOutOfSyncOnly=true
  appProjectList:
    items:
    - apiVersion: argoproj.io/v1alpha1
      kind: AppProject
      metadata:
        name: code-with-quarkus
        namespace: aaa
      spec:
        destinations:
        - namespace: aaa
          server: https://kubernetes.default.svc
        sourceRepos:
        - https://github.com/quarkiverse/code-with-quarkus.git
  items:
  - apiVersion: argoproj.io/v1alpha1
    kind: AppProject
    metadata:
      name: code-with-quarkus
      namespace: aaa
    spec:
      destinations:
      - namespace: aaa
        server: https://kubernetes.default.svc
      sourceRepos:
      - https://github.com/quarkiverse/code-with-quarkus.git
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: code-with-quarkus-deploy
      namespace: aaa
    spec:
      destination:
        namespace: aaa
        server: https://kubernetes.default.svc
      project: code-with-quarkus
      source:
        helm:
          valueFiles:
          - values.yaml
        path: .helm/kubernetes/code-with-quarkus
        repoURL: https://github.com/quarkiverse/code-with-quarkus.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 10m
        syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
        - ApplyOutOfSyncOnly=true
applicationList:
  items:
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: code-with-quarkus-deploy
      namespace: aaa
    spec:
      destination:
        namespace: aaa
        server: https://kubernetes.default.svc
      project: code-with-quarkus
      source:
        helm:
          valueFiles:
          - values.yaml
        path: .helm/kubernetes/code-with-quarkus
        repoURL: https://github.com/quarkiverse/code-with-quarkus.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 10m
        syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
        - ApplyOutOfSyncOnly=true
```
@iocanel

**Comment by cmoulliard** [comment]
Situation is a bit better with latest commits >> 77ff13a but there is still a problem as `applicationNamespace` is not set
```
 ./mvnw clean package -DskipTests -Dquarkus.argocd.namespace=aaa -Dquarkus.argocd.applicationNamespace=bbb
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: code-with-quarkus
  namespace: aaa
spec:
  destinations:
  - namespace: aaa
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/quarkiverse/code-with-quarkus.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: code-with-quarkus-deploy
  namespace: aaa
spec:
  destination:
    namespace: aaa
    server: https://kubernetes.default.svc
  project: code-with-quarkus
  source:
    helm:
      valueFiles:
      - values.yaml
    path: .helm/kubernetes/code-with-quarkus
    repoURL: https://github.com/quarkiverse/code-with-quarkus.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
```
**Important**: The namespace where the `Application or Project` CR should be deployed are 
```
namespace: openshift-gitops << Control's plane namespace of ArgoCD on OCP
namespace: argocd << Control's plane namespace of ArgoCD on kubernetes
```

**Comment by iocanel** [comment]
> ./mvnw clean package -DskipTests -Dquarkus.argocd.namespace=aaa -Dquarkus.argocd.applicationNamespace=bbb

The property name used is wrong. You should try `/mvnw clean package -DskipTests -Dquarkus.argocd.namespace=aaa -Dquarkus.argocd.application-namespace=bbb` instead.

BTW, I verified that it works both from the build, application.properties and cli.

**Comment by iocanel** [comment]
> **Important**: The namespace where the `Application or Project` CR should be deployed are
> 
> ```
> namespace: openshift-gitops << Control's plane namespace of ArgoCD on OCP
> namespace: argocd << Control's plane namespace of ArgoCD on kubernetes
> ```
Agree, but this is something that needs to be part of a different pull request.

**Pull request merged**
